name: 'npm updates report'
description: 'npm-check-updates report for pull-request creation'

inputs:
  package-manager:
    description: 'Choose package manager (npm or yarn)'
    required: false
    default: 'npm'

outputs:
  commentUrl:
    description: 'Comment URL'

runs:
  runs:
    using: "node12"
    main: "dist/index.js"